service: dca-cron-lambda-function

provider:
  name: aws
  runtime: nodejs22.x
  region: ${opt:region, 'us-east-2'}
  memorySize: 512
  timeout: 300 # 5 minutes = 300 seconds
  environment:
    DCA_EXECUTOR_ADDRESS: ${env:DCA_EXECUTOR_ADDRESS}
    RPC_URL: ${env:RPC_URL}
    PRIVATE_KEY: ${env:PRIVATE_KEY}
    DATABASE_URL: ${env:DATABASE_URL}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: "*"

package:
  patterns:
    - "!node_modules/.prisma/client/libquery_engine-*"
    - "node_modules/.prisma/client/libquery_engine-rhel-*"
    - "node_modules/@prisma/client/**"
    - "prisma/**"

functions:
  executeDCAPlans:
    handler: index.handler
    events:
      - schedule: rate(5 minutes)
    environment:
      NODE_ENV: production

  updatePortfolioValues:
    handler: portfolio-updater.handler
    events:
      - schedule: cron(0 12 * * ? *) # Daily at 12:00 PM UTC (adjust timezone as needed)
    environment:
      NODE_ENV: production
